### ISSUE TITLE
!vos not updating timely

### ISSUE THREAD

**Issue by ItsJord** [AoDude/RuneInfo#10]
Hey all.

Used to be a part of a server that was using RuneCord. Later on joined a server that had RuneInfo. Most of the features are really useful, so thanks for that!

Lately however I've noticed the !vos command does not return updated information at all, and not just once, many times. Just this hour, I tried using the !vos command three times (:03, :11 and :17) and at all given times it returned the VOS of the previous hour:

http://i.imgur.com/rhG1AhG.png

While the current vos is actually Crwys & Cadarn, as shown here on my other server with the RuneCord bot:

http://i.imgur.com/58yFzQ1.png

Any ideas what the issue could be? I have tried different channels within the same server too, get the wrong output everywhere.

Thanks in advance,
Jordy

Edit: Just checked again (:35) and it finally updated. Way too late though, hence the post ;-)

**Comment by AoDude** [comment]
Thanks for the report, I have seen this a few times myself. The source that I use to get vos seems to be off... I have some other ideas on where to get the information (hopefully more accurately). I will put it on my list of things I am adding to V5 which hopefully isn't too far away.

**Comment by ItsJord** [comment]
Alright, thanks for the quick reply! Good luck on the new version 👍

**Comment by AoDude** [comment]
I rewrote the vos code to get info from a much better source. This will ship with v5.

**Comment by ItsJord** [comment]
Might also want to check out Runesphere:

http://i.imgur.com/o5rYta5.png

http://i.imgur.com/Tx7WX76.png

**Comment by AoDude** [comment]
I pushed a rewrite to v4 for that command just a few minutes ago. I am unable to be in game at the moment to check it, but the output seems more in line with what it should be. (seems I made a math error originally converting the lotus date float into javascript date-time) Using moment.js now, should be accurate, but would really like in game confirmation.

**Comment by ItsJord** [comment]
http://i.imgur.com/rVkmrjs.png

Hmm. Sheet shows next sphere is in 1h 8 minutes from now but RuneInfo says 2 hours 7 minutes. I've always used this sheet so I'm fairly sure it is correct. If you want I'll go check when it's time, though.

**Comment by AoDude** [comment]
Must be another math error, as that sheet is where the seed values are coming from... Let me look at the math again...

**Comment by AoDude** [comment]
Just updated it again, missed a UTC call, so it was basing those times in local... If you could check about the time of the command, that would be helpful.

**Comment by ItsJord** [comment]
http://i.imgur.com/anln2y6.png

Looking all good now! Cheers for the good work =)

**Comment by ItsJord** [comment]
Sorry for being impatient but do you have any release date for V5?

Would love to see this fixed so we can get rid of the other bot, it's confusing people :P

**Comment by AoDude** [comment]
My goal is this month. My drop dead date is ~36 days from today. I can say I have gotten a lot of the major things worked out, except one (which might take the longest, because it depends on D.JS/the discord library I use, and not so much me.)

I mostly just have polishing and bug testing left before v5 will be ready to ship.

**Comment by ItsJord** [comment]
Ok thanks dude, if I can help with anything of that just let me know.

**Comment by AoDude** [comment]
Are you in the RuneInfo discord guild?

**Comment by ItsJord** [comment]
Nope I am not. Just in my raid group and ex clan's discord atm.
