### ISSUE TITLE
Automatic daily commands

### ISSUE THREAD

**Issue by Mr-Frosty-Tom** [AoDude/RuneInfo#11]
Hey there,

I was wondering if it was possible to make it so you can configure the bot to run daily commands?

For example the PVM rotations, some of these change daily or weekly, would it be possible to configure the bot so that it runs the commands after "game reset" in a designated channel?

Cheers,
Tom

**Comment by AoDude** [comment]
Apologies, I thought I had responded to this. This is not something feasible to add for a bot of this size (number of guilds). There is something built into discord though that is meant for this purpose, called webhooks. I have been helping Freud build a gitbook explaining how to set this up. It's still a Work In Progress, but here is a link: https://www.gitbook.com/book/rsnfreud/webhook/details
