### ISSUE TITLE
!price list prices [suggestion]

### ISSUE THREAD

**Issue by MorkHub** [AoDude/RuneInfo#13]
`!price` is a brilliant command, implemented fantastically. The only exception to this is that when there are multiple results for an item, the prices are not listed with the items, and I think this should be implemented, so that users do not have to use the `!price` command again for each item

**Comment by AoDude** [comment]
As much as I would like to be able to do that, it isn't feasible.

The list of items comes from my database, as a helper to help you find the item you are looking for (including items which share the same name, so you can lookup via item id). The prices come from the grand exchange api, with a cooldown of 4 hours (where prices are cached). Say for instance you ran `!price cape` there are 75 results for cape, so getting the price for all of them would take 75 api hits. And to avoid being locked out of the api for 15 minutes, I need to keep the average api request under 1 request per 5 seconds. So it would take over 6 minutes to get all of the capes, when you are likely just looking for one in particular.

Using the !price command and getting just database results from me is "free" as it doesn't cost any api requests.
