### ISSUE TITLE
!pvm command # of resets is incorrect/ambiguous (1 extra)

### ISSUE THREAD

**Issue by acarcher** [AoDude/RuneInfo#16]
For example:

It is 02:35 May 18th (Thursday) in game time.

!pvm returns
Vorago
Current Rotation: The End - for 7 more resets.
Araxxor
The current blocked tunnel: Minions - for 1 more resets.

As Vorago will reset 00:00 May 24 (Wednesday) in game time, there are only 6 more resets (May 19, 20, 21, 22, 23, 24) until ceilings.

As Araxxor will change at 00:00 May 19 (Friday) in game time, there are 0 more resets (May 19 is the next reset) until 1/3.

**Comment by AoDude** [comment]
This should now be fixed.
