### ISSUE TITLE
Vis Wax command bug

### ISSUE THREAD

**Issue by Anuhbis** [AoDude/RuneInfo#17]
I'm pretty sure the vis wax command (!viswax) is bugged. The image doesn't load and leaves and an empty space. I tested it on 3 different computers, 2 windows10 and 1 windows7.

**Comment by AoDude** [comment]
This is a bug with Discord caching the image on their servers. There is nothing I can do to fix their caching error, but now if you click on the title of the embed, it will take you to the URL of the image.
