### ISSUE TITLE
You should not be seeing this

### ISSUE THREAD

**Issue by jmsf97** [AoDude/RuneInfo#19]
This error message appeared when I tried to use the command !event. Used it twice and I got the error.
[http://imgur.com/BN80Ge1](http://imgur.com/BN80Ge1)

**Comment by AoDude** [comment]
I just restarted RuneInfo, it hasn't seemed to happen again so far. I know Discord has disconnected the websocket connection a couple times today, and it has been buggy. Hopefully this resolves that issue for now though. I will keep watching for it.

**Comment by AoDude** [comment]
I haven't seen anything since the restart. Closing this issue, thanks.
