### ISSUE TITLE
Vis Wax combination hasn't been working for some time now

### ISSUE THREAD

**Issue by Seravailbug** [AoDude/RuneInfo#21]
![image](https://user-images.githubusercontent.com/31406041/29770327-d40dd918-8bee-11e7-82d6-2e9548f91c6f.png)
This is all it ever shows, has been happening for a few weeks now.

**Comment by RSNFreud** [comment]
We're working on a new vis command but still in early progress. This is a problem with the thread we take the info from and we have to manually update to fix it.
