### ISSUE TITLE
Unable to fetch profile  for "username"

### ISSUE THREAD

**Issue by CuteKitty92** [AoDude/RuneInfo#22]
When doing commands like alog , gainz and wsid  sometimes an issue happens  where it says unable to fetch profile and then persons username ,  it seems to be only those commands which are doing it .

**Comment by AoDude** [comment]
All of those commands and a few more utilize the runemetrics api which has been acting up like that for months. It has been reported to jagex, they are aware of the issue, but it hasn't been a priority for them to fix yet.

**Comment by AoDude** [comment]
https://twitter.com/aodude1234/status/877203595590062080

**Comment by RSNFreud** [comment]
Fixed!
