### ISSUE TITLE
Who's in for Vorago tonight?

### ISSUE THREAD

**Issue by Borithel** [AoDude/RuneInfo#26]
Often times in my discord someone will want to organise a boss for a certain time, people usually indicate their participation with a comment or reacting with a specific emoji (Upvote/Downvote in my server). The issue with this is using one emoji stops displaying usernames past 3 people, so I don't know who wants to come. And comments just push the voting up, so people don't readily see it anymore.
 ![image](https://user-images.githubusercontent.com/34362612/33752248-b4eb16e4-dbae-11e7-92b1-f18c7bcf4c46.png)
A clean format that displays who wants to go to the boss by displaying who reacted with a Yes, No, or Maybe would make my group organising boss trips much easier. An additional function could be the bot messaging the host of the boss organisation when a threshold of people were met, as well as placing a limit function so it's first come first serve and stops counting the reactions.

I took a brief look around for a function such as this within other bots
 but I couldn't find any. If the base of this suggestion exists within another bot already i'd be okay with that too.

**Comment by AoDude** [comment]
While this would be possible, this is out of scope for this project. This seems like a feature for a generic event planner bot.
