### ISSUE TITLE
!compare is broken

### ISSUE THREAD

**Issue by Cabola** [AoDude/RuneInfo#31]
When ever I try to do a compare I either get "Bad Request" or "Couldn't get playerinfo from the api at this time." as a reply back from the bot. This has been going on for over a week now..

Here's a pic of it from today:
![ss-runeinfo](https://user-images.githubusercontent.com/19853946/36063073-8b05c5ac-0e78-11e8-8e7d-c9283510bf22.png)

**Comment by RSNFreud** [comment]
This is an issue on Jagex's end that we are waiting on a fix for.
