### ISSUE TITLE
Not really a bug..

### ISSUE THREAD

**Issue by Sonicranqe** [AoDude/RuneInfo#34]
More a request.. Can we get a !merchant command (travelling merchant in fishing hub) that shows todays items?

**Comment by RSNFreud** [comment]
We'd need a source to take it from. Like a spreadsheet or something.... Also requests are welcome here it's not just reporting bugs

**Comment by Sonicranqe** [comment]
Tood bad i dont know how to :(

All i managed to find was this:

http://runescape.wikia.com/wiki/Travelling_Merchant%27s_Shop?action=edit&section=2

Its updated basically, any chance you could use whats on there for a command?

**Comment by AoDude** [comment]
This is implemented in Dev now that a consistent data source is available. I still have some work to do on it before it makes it's way into release, but it should be there soon.
