### ISSUE TITLE
Is it possible for Runeinfo to listen to webhooks?

### ISSUE THREAD

**Issue by SageBlack** [AoDude/RuneInfo#37]
Just a question. I want to know if I can use Mee6's timer plugin and trigger the Runeinfo bot to respond if its a specific bot command. See attached: https://i.imgur.com/sY4FpxN.png

I asked in the Mee6 Community discord and got this response. https://i.imgur.com/A4E6P1n.png

Is there any way to get this feature working by enabling the Runeinfo bot to listen to webhooks?

**Comment by AoDude** [comment]
no
