### ISSUE TITLE
Photo on !alog and other commands not updated

### ISSUE THREAD

**Issue by Bleepey** [AoDude/RuneInfo#38]
I couldn't read anywhere if there's a wait for this but it's been just short of a day and the image that appears when i check my alog and other things that include the image on my adventurer's log isn't updated and matching the change i made in game; IGN is Bleepy if you want to test the difference between the two thanks

**Comment by AoDude** [comment]
Discord caches images based on the route for some time. Changes to your in game avatar (forum avatar) ect, will take some time to show the change.
