### ISSUE TITLE
Leaving Server

### ISSUE THREAD

**Issue by Aytrix** [AoDude/RuneInfo#40]
The bot refuses to stay in the server.  It's not being kicked, and it's not being kicked.  I re-invite it and there is a second delay and it leaves again.
![capture](https://user-images.githubusercontent.com/39447081/40274006-6375f7f6-5b89-11e8-9391-62b84ec9c79f.PNG)
![capture1](https://user-images.githubusercontent.com/39447081/40274007-63881148-5b89-11e8-898a-8e3890cf68d1.PNG)

**Comment by AoDude** [comment]
You were helped in the bot support guild.
