### ISSUE TITLE
Improvement on style?

### ISSUE THREAD

**Issue by Wh1spr** [AoDude/RuneInfo#41]
*Suggestion to improve style*
In gainz, stats,... it might be possible to outline the numbers like xp to the right, so that numbers with the same magnitude are on a vertical line. I think it'll look better than what you currently have (a bit jagged imo)

**Comment by AoDude** [comment]
by outline, you mean right aligned text. I need to look into the options I have available. This may or may not be easily possible.

**Comment by AoDude** [comment]
This has been implemented as of tonight
