### ISSUE TITLE
Player Owned Farm merchants

### ISSUE THREAD

**Issue by Dovry** [AoDude/RuneInfo#45]
Add a tracker for what pen size merchant is currently at the farm, and display which ones will arrive in the next 2 days
![image](https://user-images.githubusercontent.com/15201298/45016337-9894cd00-b024-11e8-90cd-39fee6762a80.png)

commands:
!pof
!pofmerch
!farmmerch

**Comment by RSNFreud** [comment]
Already done! Use the !trader command!
