### ISSUE TITLE
!gainz Not showing data

### ISSUE THREAD

**Issue by Lucbeard** [AoDude/RuneInfo#55]
![gainz](https://user-images.githubusercontent.com/50744718/57934223-cbb28000-7884-11e9-81a9-2f07434c4f8b.PNG)

Gainz isn't working for channel. Tried registering with runeclan to get the clan info updated from there but their account activation must not be working since I requested it at least a dozen times for two different accounts and I never receive an email. Is there any other way to fix this?

**Comment by DarkPyroNinja** [comment]
Hey, this account seems to be fixed, and should now be showing data. For future reference, you can use the image below and find your account. From there, click a button that either says to start tracking, or to force track if it is not in a clan. Hope this helps!
![image](https://user-images.githubusercontent.com/29024572/57945125-a29ee900-789e-11e9-933a-146e06e47b94.png)
