### ISSUE TITLE
!commands

### ISSUE THREAD

**Issue by zaboomafo** [AoDude/RuneInfo#56]
when I type !commands in our admin bot channel it says I have the runeinfo bot blocked, but it will let me use !stats and other runeinfo commands like !getclan etc. When I went to check to see if I accidently blocked the bot it says I haven't. thoroughly confused.

**Comment by zaboomafo** [comment]
oops srry misclick

**Comment by AoDude** [comment]
The bot cannot dm you, this is the response that happens on that error.
