### ISSUE TITLE
Vis command to include base cost of each rune

### ISSUE THREAD

**Issue by Foxite** [AoDude/RuneInfo#59]
You either have to memorize it, look it up every time, or simply go twice, if you want to know how many runes you need to buy for the Rune Goldberg machine. For instance, I thought I needed a few more than 1000 body runes today, but the base cost is 2000, so I had to make a trip back.

It would be very useful to include the base cost of each rune in the response. I don't think this changes regularly, so it could be as simple as hard-coding the values.

**Comment by AoDude** [comment]
The values are known internally for calculating the most efficient alt to choose. However the base amount doesn't fit graphically with the rest of the image. Typically players just have an excess of all cheap runes in there bank, so it's not a problem.
