### ISSUE TITLE
!07price Dragon bones

### ISSUE THREAD

**Issue by WarriorOSRS** [AoDude/RuneInfo#6]
Hi, when I use !07price Dragon bones, it shows babydragon bones instead of dragon bones.

**Comment by AoDude** [comment]
This is a known issue, it has to do with my current method of searching by item name (using a 3rd party website). I would love to rewrite 07price to work like the RS3 version (which searches a local database) but I haven't found the similar api's to crawl to keep the items up to date.

It may be a while before this gets a fix, but it is on my radar.

**Comment by WarriorOSRS** [comment]
Oh okay, no worries.

**Comment by WG-Mojo** [comment]
As a workaround for now you can type "!07price 536" which is the GE id number of dragon bones and will give you the correct price.

**Comment by AoDude** [comment]
This will be fixed in the v5 release. Currently mid rewrite now.
