### ISSUE TITLE
Add farming requests

### ISSUE THREAD

**Issue by alercah** [AoDude/RuneInfo#63]
It would be nice not to have to jump to the farm each time I want to see what they are.

**Comment by RSNFreud** [comment]
Hi,

I do not understand what you mean by this? Can you explain further....

**Comment by alercah** [comment]
https://runescape.wiki/w/Farming_requests

The easy one changes daily, and as far as I know the only way to check it
in game is to visit the farm.

**Comment by RSNFreud** [comment]
So theres no way for us to check then unless someone does it for us.
