### ISSUE TITLE
!vis image not displaying

### ISSUE THREAD

**Issue by rhihuahua** [AoDude/RuneInfo#67]
![image](https://user-images.githubusercontent.com/73802182/97818817-da028f00-1cf8-11eb-8c15-d60638d39f93.png)

!vis command returns an embed, but there is no image attached/displaying. Issue noticed 20/10/2020

**Comment by RSNFreud** [comment]
The !vis command is temporarily down due to the move in hardware. We are aware it has been acting up. There is currently no ETA on a fix. Best place to hear updates would be in the discord server.
