### ISSUE TITLE
!gainz not working with just my username, all else works!

### ISSUE THREAD

**Issue by DaanV1** [AoDude/RuneInfo#7]
!gainz doesn't work with my username and my username only. It works for all of my friends accounts plus some random ones too. Mine doesn't, it shows only 0 xp gained.
I have my Adventures log set to public (been like that for three years) and RuneTrack has been tracking since 2013.

Reproduction Steps:

    type !gainz Daan V

Expected behavior:
Shows table of nothing gained when I've been playing all day.

Observed behavior:

.Shows table of nothing gained when I've been playing all day.

Screenshots and GIFs

![nothing](https://cloud.githubusercontent.com/assets/24628127/21341765/6621615c-c68e-11e6-9031-6441a45c4300.PNG)

Bot version: 4.2.4 [Enter Bot version here]

Additional information:

    Problem started happening recently, didn't happen in an older version of RuneInfo: [Don't know, only tested 4.2.4]
    Problem can be reliably reproduced, doesn't happen randomly: [Yes!]

**Comment by AoDude** [comment]
For gains to work, you must be being tracked by runeclan.

**Comment by AoDude** [comment]
As you have resolved this issue, I am closing it: http://puu.sh/sYeEU/707a187ebb.png
