### ISSUE TITLE
The !alog and !portables commands are not showing results

### ISSUE THREAD

**Issue by Vorthas** [AoDude/RuneInfo#8]
Whenever I want to use the !alog command or the !portables command, the RuneInfo bot makes an empty post in both the Discord app and Discord website.  I've attached a screenshot showing the results from the Discord app when I use both of those commands.  Oddly enough, other people are able to see the results of these commands.  I have completely uninstalled and reinstalled Discord in case it's a problem with my installation, but that did not seem to fix it.

![empty runeinfo posts](https://cloud.githubusercontent.com/assets/24818280/21534888/4481be4c-cd33-11e6-8d65-82e7780913dd.jpg)

**Comment by AoDude** [comment]
It appears you have embeds toggled off. Click the gear next to your name, go down to `Text & Images` and turn on `Show website preview info from links posted in chat`

![](http://puu.sh/t4aOf/6cf61dd3dd.png)

**Comment by Vorthas** [comment]
Alright, that fixed it, thanks!  Sorry for wasting your time.

**Comment by AoDude** [comment]
No worries! Let me know if you have any more issues. Feel free to join the official discord guild here if you have any more questions: https://discord.gg/TrDnKtQ
