### ISSUE TITLE
!alog command not working

### ISSUE THREAD

**Issue by rattlesnakes** [AoDude/RuneInfo#9]
When someone tries using the command "!alog <username>" the bot says "Insufficient permissions, missing: Embed Links"

**Comment by rattlesnakes** [comment]
Just saw a previous issue where a user had "Show website preview info from links pasted into chat." unchecked, but it is checked for me. Just fyi :-)

**Comment by AoDude** [comment]
Alog, aswell as many other commands use embed messages for cleaner/nicer looking output. For those commands to work, the bot needs the permission "Embed Links". The !invite command will actually list every command that requires elevated permissions beyond the normal Read/Write/Read Message History.

Simply going into your guild settings, and creating a role for RuneInfo or editing an existing role with the additional permissions will allow the bot to use those commands.

**Comment by rattlesnakes** [comment]
Tyvm for fast response. Will relay the message and give it a shot.

**Comment by rattlesnakes** [comment]
http://prnt.sc/dvaysr this is a screenie from one of our admins. Any other ways to possibly fix?

**Comment by AoDude** [comment]
Few things to check then... Check permission overwrites in the channel itself. If @everyone has deny on that channel, and there is no overwrite for the @bot role with an allow, then the bot wouldn't have permission.

Feel free to hop in https://discord.gg/TrDnKtQ for trouble shooting chat.

**Comment by AoDude** [comment]
Since I haven't heard back from you in 9 days, I assume you have this issue sorted. Feel free to open again, or hop in my support guild if you need any more help.
